import { TimelineActivity } from './types';

export const dummyTimelineActivities: TimelineActivity[] = [
  {
    id: '1',
    type: 'lead_created',
    title: 'New Lead Created',
    description: 'Lead was added to the system via web form.',
    userName: 'Admin',
    timestamp: new Date().toISOString(),
    status: 'New',
    notes: 'Source: Website contact form.',
    metadata: { source: 'Web Form', ip_address: '192.168.1.45' },
  },
  {
    id: '2',
    type: 'lead_assigned',
    title: 'Lead Assigned to Manager',
    description: 'Lead assigned to Sarah Johnson for follow-up.',
    userName: 'Admin',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    status: 'Assigned',
    metadata: { assigned_to: 'Sarah Johnson', role: 'Manager' },
  },
  {
    id: '3',
    type: 'call_completed',
    title: 'Outbound Call Completed',
    description: 'Spoke with the lead. Interested in enterprise plan.',
    userName: 'Sarah Johnson',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    status: 'Connected',
    notes: 'Call lasted 4 minutes 32 seconds. Lead wants a demo next week.',
    metadata: { duration: '272s', call_type: 'Outgoing' },
  },
  {
    id: '4',
    type: 'followup_scheduled',
    title: 'Follow-up Scheduled',
    description: 'Demo call scheduled for next Tuesday.',
    userName: 'Sarah Johnson',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2.5).toISOString(),
    status: 'Pending',
    notes: 'Send calendar invite and Zoom link.',
    metadata: { follow_up_date: '2026-05-18 10:00 AM' },
  },
  {
    id: '5',
    type: 'email_sent',
    title: 'Proposal Email Sent',
    description: 'Sent pricing proposal PDF to the lead.',
    userName: 'Sarah Johnson',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    status: 'Sent',
    metadata: { subject: 'Enterprise Pricing Proposal', attachments: '1' },
  },
  {
    id: '6',
    type: 'meeting_done',
    title: 'Demo Meeting Completed',
    description: 'Walked through the CRM dashboard and reporting features.',
    userName: 'Sarah Johnson',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    status: 'Completed',
    notes: 'Lead seemed very interested. Asked for a 14-day trial.',
    metadata: { meeting_type: 'Video Call', platform: 'Zoom' },
  },
  {
    id: '7',
    type: 'status_changed',
    title: 'Status Updated to Interested',
    description: 'Lead status changed from New to Interested.',
    userName: 'Sarah Johnson',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24.5).toISOString(),
    status: 'Interested',
    metadata: { old_status: 'New', new_status: 'Interested' },
  },
  {
    id: '8',
    type: 'payment_received',
    title: 'Payment Received',
    description: 'First installment of $2,400 received.',
    userName: 'Accounts Team',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    status: 'Paid',
    notes: 'Invoice #INV-2026-0042',
    metadata: { amount: '$2,400.00', invoice: 'INV-2026-0042' },
  },
  {
    id: '9',
    type: 'lead_closed',
    title: 'Lead Closed – Won',
    description: 'Deal finalized and contract signed.',
    userName: 'Sarah Johnson',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 49).toISOString(),
    status: 'Won',
    notes: 'Contract value: $24,000/year. Onboarding scheduled for next Monday.',
    metadata: { deal_value: '$24,000', contract_term: '12 months' },
  },
  {
    id: '10',
    type: 'lead_assigned',
    title: 'Lead Assigned to Agent',
    description: 'Lead assigned to Michael Chen for initial outreach.',
    userName: 'Sarah Johnson',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    status: 'Assigned',
    metadata: { assigned_to: 'Michael Chen', role: 'Agent' },
  },
  {
    id: '11',
    type: 'call_completed',
    title: 'Inbound Call Received',
    description: 'Lead called back to ask about integrations.',
    userName: 'Michael Chen',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 73).toISOString(),
    status: 'Connected',
    metadata: { duration: '180s', call_type: 'Incoming' },
  },
  {
    id: '12',
    type: 'email_sent',
    title: 'Integration Guide Sent',
    description: 'Emailed the API integration guide and documentation links.',
    userName: 'Michael Chen',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 74).toISOString(),
    status: 'Sent',
    metadata: { subject: 'API Integration Guide v2.1' },
  },
];
